import type { Database } from "@/types/database";

/**
 * Ergonomic aliases over the generated database types.
 *
 * Hand-written and kept out of `database.ts` on purpose: that file is
 * regenerated by the Supabase CLI and anything added to it would be lost on the
 * next schema change.
 *
 * Once tables exist, this is the vocabulary the rest of the app uses:
 *
 *     type Profile     = Tables<"profiles">;
 *     type NewProfile  = TablesInsert<"profiles">;
 *     type CallStatus  = Enums<"call_status">;
 *
 * Deriving from the generated types rather than declaring row shapes by hand is
 * the whole point: a column rename becomes a compile error instead of a bug.
 */

export type PublicSchema = Database["public"];

export type TableName = keyof PublicSchema["Tables"];
export type Tables<T extends TableName> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends TableName> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends TableName> = PublicSchema["Tables"][T]["Update"];

export type ViewName = keyof PublicSchema["Views"];
export type Views<T extends ViewName> = PublicSchema["Views"][T]["Row"];

export type EnumName = keyof PublicSchema["Enums"];
export type Enums<T extends EnumName> = PublicSchema["Enums"][T];

export type FunctionName = keyof PublicSchema["Functions"];
export type FunctionArgs<T extends FunctionName> = PublicSchema["Functions"][T]["Args"];
export type FunctionReturns<T extends FunctionName> = PublicSchema["Functions"][T]["Returns"];
